sudo: required
services: 
  - docker

before_install:
  - docker build -t simpletest -f Dockerfile.dev .

script: 
  - docker run simpletest npm run test -- --coverage --detectOpenHandles --forceExit

